apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - image: brbarnett/payment-api:latest
        name: payment-api
        ports:
        - containerPort: 80
        env:
        - name: AMQP_SIDECAR_URI
          value: http://payment-api-amqp-sidecar/payments/payments.create
        - name: PAYMENT_PROCESSOR_URI
          value: http://payment-processor
      - image: brbarnett/amqp-sidecar@sha256:363b798c22d6e6a8ffcceffaac6a15061fff62e11be0c11ec703ee34dc343fb1
        name: amqp-sidecar
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_HOSTNAME
          value: message-broker-rabbitmq
        - name: RABBITMQ_USERNAME
          value: rabbitmq
        - name: RABBITMQ_PASSWORD
          value: rabbitmq